spring:
  application:
    name: gateway-serveer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
    gateway:
#      filter:
#        request-header-to-request-uri:
#          enabled:
      routes:
        - id: pub-server
          uri: lb://pub-server
          predicates:
            - Path=/rest/pub-server/**

  profiles:
    active: dev

